server:
  port: 8090
  servlet:
    context-path: /
    
spring:
  rabbitmq:
    host: rabbitmq-server
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      bindings:
        input:
          destination: primBroadcastAll 
          #group: primSupervisorQueue
        output:
          destination: primReceiveFromAll
          #group: primWorkerQueue 
           
worker:
  id: ${WORKER_ID}           
  
    
 