version: '3.4'

services:

 # rabbitmq-server
  rabbitmq-server:
    image: rabbitmq:3.8.5-management
    hostname: "my-rabbit"
    ports:
      # host:container
      - "15672:15672"
      - "5672:5672"

  # worker
  worker-1:
    image: worker:0.0.1-SNAPSHOT
    environment:
      - WORKER_ID=0

  # worker
  worker-2:
    image: worker:0.0.1-SNAPSHOT
    environment:
      - WORKER_ID=1

  # worker
  worker-3:
    image: worker:0.0.1-SNAPSHOT
    environment:
      - WORKER_ID=2

