server:
  port: 8080
  servlet:
    context-path: /minimum-spanning-tree
    
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
                
  cloud:
    stream:
      bindings:
        input:
          destination: primReceiveFromAll
          group: primWorkerQueue
        output:
          destination: primBroadcastAll
           
worker-number: 3                      
